# Generated by Django 4.2 on 2024-06-11 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('job_title', models.CharField(blank=True, max_length=32, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=128, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('remark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('scanned_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_api.staff')),
            ],
        ),
    ]
