# Generated by Django 4.2 on 2024-06-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ata_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='created_at',
            new_name='issued_at',
        ),
    ]
