# Generated by Django 4.2 on 2024-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_api', '0003_rename_total_amount_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='updated_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
