# Generated by Django 4.2 on 2024-06-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ata_api', '0004_balance_updated_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='updated_value',
        ),
    ]
