# Generated by Django 4.2 on 2024-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_api', '0005_remove_balance_updated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('recharge', 'Recharge')], default='expense', max_length=10, null=True),
        ),
    ]
