# Generated by Django 4.2 on 2024-05-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrfad_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('click', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_clicks', to='gdrfad_api.language')),
            ],
        ),
    ]
