# Generated by Django 4.2 on 2024-05-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrfad_api', '0002_languageclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('click', models.IntegerField(default=0)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions_clicks', to='gdrfad_api.emotion')),
            ],
        ),
    ]
