# Generated by Django 4.2 on 2024-05-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrfad_api', '0005_alter_courseclick_course_alter_emotionclick_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='gdrfad_api.course'),
        ),
    ]
